alter table public.events add column if not exists slug text;
alter table public.events add column if not exists time_label text;
alter table public.events add column if not exists status text not null default 'draft';
alter table public.events add column if not exists source_name text;
alter table public.events add column if not exists access text;
alter table public.events add column if not exists accessibility text;
alter table public.events add column if not exists art text not null default 'stage';
alter table public.events add column if not exists access_52 boolean not null default false;
alter table public.events add column if not exists verified_at timestamptz;
alter table public.events add column if not exists verified_by text;

do $$ begin
  alter table public.events add constraint events_status_check
    check (status in ('draft','review','verified','published','archived','rejected'));
exception when duplicate_object then null;
end $$;

create unique index if not exists events_slug_idx on public.events (slug) where slug is not null;
create index if not exists events_status_date_idx on public.events (status, starts_at);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('event','correction')),
  status text not null default 'received' check (status in ('received','review','resolved','archived')),
  name text not null,
  email text not null,
  organization text,
  submitter_relation text check (submitter_relation in ('public','organizer')),
  organization_role text,
  promotion_interest boolean not null default false,
  newsletter_opt_in boolean not null default false,
  event_title text,
  event_reference text,
  event_date date,
  end_date date,
  date_mode text check (date_mode in ('single','range')),
  time_label text,
  start_time time,
  end_time time,
  time_mode text check (time_mode in ('single','range')),
  venue text,
  area text,
  category text,
  condition text,
  source_url text,
  accessibility text,
  details text,
  privacy_notice_version text not null,
  reviewed_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or event_date is null or end_date >= event_date)
);

create index if not exists submissions_status_created_idx on public.submissions (status, created_at desc);
create index if not exists submissions_kind_created_idx on public.submissions (kind, created_at desc);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  status text not null default 'consent_recorded' check (status in ('consent_recorded','unsubscribed')),
  consent_source text not null check (consent_source in ('event_form','correction_form')),
  consent_notice_version text not null,
  consented_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists newsletter_subscribers_status_idx
  on public.newsletter_subscribers (status, consented_at desc);

alter table public.events enable row level security;
alter table public.submissions enable row level security;
alter table public.newsletter_subscribers enable row level security;

revoke all on table public.events from anon, authenticated;
revoke all on table public.submissions from anon, authenticated;
revoke all on table public.newsletter_subscribers from anon, authenticated;
grant all on table public.events to service_role;
grant all on table public.categories to service_role;
grant all on table public.parishes to service_role;
grant all on table public.venues to service_role;
grant all on table public.submissions to service_role;
grant all on table public.newsletter_subscribers to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.create_submission_with_consent(payload jsonb)
returns setof public.submissions
language plpgsql
security definer
set search_path = ''
as $$
declare created public.submissions;
begin
  insert into public.submissions (
    kind, name, email, organization, submitter_relation, organization_role,
    promotion_interest, newsletter_opt_in, event_title, event_reference,
    event_date, end_date, date_mode, time_label, start_time, end_time, time_mode,
    venue, area, category, condition, source_url, accessibility, details,
    privacy_notice_version
  ) values (
    payload->>'kind', payload->>'name', lower(payload->>'email'), nullif(payload->>'organization', ''),
    nullif(payload->>'submitter_relation', ''), nullif(payload->>'organization_role', ''),
    coalesce((payload->>'promotion_interest')::boolean, false),
    coalesce((payload->>'newsletter_opt_in')::boolean, false),
    nullif(payload->>'event_title', ''), nullif(payload->>'event_reference', ''),
    nullif(payload->>'event_date', '')::date, nullif(payload->>'end_date', '')::date,
    nullif(payload->>'date_mode', ''), nullif(payload->>'time_label', ''),
    nullif(payload->>'start_time', '')::time, nullif(payload->>'end_time', '')::time,
    nullif(payload->>'time_mode', ''), nullif(payload->>'venue', ''),
    nullif(payload->>'area', ''), nullif(payload->>'category', ''),
    nullif(payload->>'condition', ''), nullif(payload->>'source_url', ''),
    nullif(payload->>'accessibility', ''), nullif(payload->>'details', ''),
    payload->>'privacy_notice_version'
  ) returning * into created;

  if created.newsletter_opt_in then
    insert into public.newsletter_subscribers (
      email, name, status, consent_source, consent_notice_version,
      consented_at, unsubscribed_at, updated_at
    ) values (
      created.email, created.name, 'consent_recorded',
      case when created.kind = 'event' then 'event_form' else 'correction_form' end,
      created.privacy_notice_version, now(), null, now()
    ) on conflict (email) do update set
      name = excluded.name, status = 'consent_recorded',
      consent_source = excluded.consent_source,
      consent_notice_version = excluded.consent_notice_version,
      consented_at = now(), unsubscribed_at = null, updated_at = now();
  end if;

  return next created;
end;
$$;

revoke all on function public.create_submission_with_consent(jsonb) from public, anon, authenticated;
grant execute on function public.create_submission_with_consent(jsonb) to service_role;
